### ISSUE TITLE
Instruction for self-hosting

### ISSUE THREAD

**Issue by Anonmusus** [NotNorom/discord-banner-bot#4]
Structure the code in a way that makes self-hosting easy with a config page where people simply need to define a few variables (like discord bot token) to make it work.

**Comment by NotNorom** [comment]
Finally added some instructions on self-hosting: https://github.com/NotNorom/discord-banner-bot#hosting-the-bot-yourself

Please leave feedback when you encounter any issues. I hope these instructions are enough
